### ISSUE TITLE
not pulling Variant Scoring from docker

### ISSUE THREAD

**Issue by andgan** [gifford-lab/GERV#1]
I'm trying to pull the variant scoring from docker, get this error:

`Using default tag: latest
Pulling repository docker.io/haoyangz/wave-variant-scoring-covar
Error: image haoyangz/wave-variant-scoring-covar:latest not found`

**Comment by matted-zz** [comment]
Thanks for your interest and the bug report.  As a quick (hopeful) fix, I just uploaded that image as `giffordlab/wave-variant-scoring-covar`, so please give that a try.  We will set up the location referred to in the documentation as an automatic build target in the future.

**Comment by andgan** [comment]
Thanks this works, can you also point me to the s3 directory where to download the raw output of k-mer model?
cheers,

**Comment by haoyangz** [comment]
Hi @andgan  Thank you for pointing out this issue, which is because the docker repo was still in private status. I just made it public, so it would be working now. Please try it out. If it works, we will remove the temporary docker image that @matted created.

**Comment by haoyangz** [comment]
To clarify your question about s3 directory, do you mean the s3 directory to the output of the [model training](https://github.com/gifford-lab/GERV/blob/master/kmm-launcher-ccm-covar/README.md) part, or to the model we trained ourselves? If it is the former, it is determined by the `bucket_name` parameter in the *_.list_ file. If it is the later, these models are still subject to future update and will be uploaded to the GERV [website](http://gerv.csail.mit.edu/).

**Comment by andgan** [comment]
Hi, yes I meant the second. thanks, I will then wait for the upload on the website. best,

**Comment by haoyangz** [comment]
@andgan I've uploaded the trained models for six TFs used in the paper. Check it out on the [website](http://gerv.csail.mit.edu/)
