### ISSUE TITLE
use without EC2?

### ISSUE THREAD

**Issue by rajanil** [gifford-lab/GERV#2]
Is there a way to install and use GERV on my local machine rather than EC2? If so, could you please point me to the relevant README that describes how to do this? (The current README states that EC2 is a prerequisite.)

thanks much!
cheers
anil

**Comment by haoyangz** [comment]
As the program requires lots of computing resources, we currently only support running it on EC2. Given you request, we will support running locally. We envision that this will be done by this month. And we will let you know here in this issue thread. Thanks!

**Comment by rajanil** [comment]
great! i look forward to using it. thanks!

**Comment by haoyangz** [comment]
Sorry the lab member responsible for a huge portion of the code base just graduated from the lab recently. We don't anticipate a locally runnable version any time soon. We will reopen this issue if more requests are made.

**Comment by crazyhottommy** [comment]
Hi, Please make a locally runnable version. I want to try it as well.

Thanks!

**Comment by haoyangz** [comment]
@rajanil @crazyhottommy The local version is available now!

**Comment by crazyhottommy** [comment]
could you please add a tutorial on it?

Thanks.

**Comment by haoyangz** [comment]
The readme is updated already.
