### ISSUE TITLE
rsa_key not found

### ISSUE THREAD

**Issue by rajanil** [gifford-lab/GERV#3]
I tried a test run with the following command and files, and get the following error.

$ docker run --rm -w `pwd` -v /home/ubuntu:/home/ubuntu -i thashim/kmm-launcher-cov /kmm/run.onestrand.r LCL/src/gerv_run_params.list LCL/cred/auth.txt

> args <- commandArgs(trailingOnly = TRUE)
> print(args)
> [1] "LCL/src/gerv_run_params.list" "LCL/cred/auth.txt"
> 
> input.list = args[1]
> cred.file = args[2]
> # ec2 default settings
> 
> price = '3.0'
> realm = 'us-east-1'
> region = paste0(realm,'d')
> ami='ami-d05e75b8'
> itype='c3.8xlarge'
> 
> print('parse credential file')
> [1] "parse credential file"
> cf=readLines(cred.file)
> cf=cf[-grep('#',cf)]
> for(sp in strsplit(cf,':')){
> -     print(sp)
> -     assign(sp[1],sp[2])
> - }
>   if(!file.exists(rsa_key)){print('check rsa key is readable')}
>   Error in file.exists(rsa_key) : object 'rsa_key' not found
>   Execution halted

$ cat LCL/cred/auth.txt
realm:us-west-2
price:1.0
region:us-west-2c
rsa_key:/home/ubuntu/.ssh/rsa_key.pem
access_key:**********
secret_key:**********
key_name:rsa_key

Any thoughts on why it's not able to read the value for 'rsa_key'?

thanks!

**Comment by thashim** [comment]
I would guess it has to do with file permissions? Does running docker with the -u flag set to your UID or copying the priv key outside the .ssh folder with more permissive permissions work? I think docker by default sets itself to root uid.

**Comment by haoyangz** [comment]
@rajanil  Could you paste the complete output on the screen here? The line 'print(sp)' should print each line of auth.txt to the screen. Do you see the right content of auth.txt in the output?

**Comment by haoyangz** [comment]
@rajanil have you figured out the problem? We would very much like to help out.

**Comment by haoyangz** [comment]
This turned out to be a bug in the prepossessing code which is supposed to remove any comments in auth.txt, but freak out when there is no comments. This has been fixed in 8d60bbd4e6a40114a56abbb297efaa8d3777580c
