### ISSUE TITLE
PW is visibple in plain text

### ISSUE THREAD

**Issue by visze** [gifford-lab/GERV#5]
Hi guys,

the public available Dockerfile contains your bitbucktet username and pw (hopefulls ony bitbucket...)

https://github.com/gifford-lab/GERV/blob/f11cc861f96a4df3ee1842a36127380755ed35df/variant-scoring/Dockerfile#L17

**Comment by haoyangz** [comment]
Thanks for spotting it and kindly letting us know. It's an empty account we set up that only has read-only permission on our Git repository (which is owned by another user ddkang). So no real damage can be done even if it's hacked. In the future, when we are sure we will no longer actively update the repository,  we will probably zip the files and put it on file server from which Docker can download.
